site_name: XOXO
site_description: Balanced diversity solver xoxo to the square.

theme:
  name: 'material'
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  generator: false
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/xoxo
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/shage

copyright: Copyright &copy; 2022 Stefan Hagen under the MIT license

repo_name: ~sthagen/xoxo
repo_url: https://git.sr.ht/~sthagen/xoxo
edit_uri: ""

plugins:
  - search
  - mkdocstrings

nav:
  - Introduction: index.md
  - Install: install.md
  - Usage: usage.md
  - API: api.md
  - Changes: changes.md
  - Test Coverage: https://codes.dilettant.life/coverage/xoxo/

markdown_extensions:
  - mkautodoc
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

extra_javascript:
